#ifndef __HEADER_H__
#define __HEADER_H__


//#define MODE_SERVEUR
#define MODE_CLIENT





#ifdef MODE_SERVEUR
#ifdef MODE_CLIENT
#error MODE CLIENT ET MODE SERVEUR ACTIVEE
#endif // MODE_CLIENT
#else
#ifndef MODE_CLIENT
#error IL FAUT ACTIVER LE MODE SERVEUR OU LE MODE CLIENT
#endif // !MODE_CLIENT
#endif // MODE_SERVEUR
#endif